version: '2'
services:
    mariadb:
        image: 'bitnami/mariadb:latest'
        environment:
          - MARIADB_USER=${DATABASE_USER}
          - MARIADB_DATABASE=bitnami_suitecrm
          - MARIADB_PASSWORD=${DATABASE_PASSWORD}
          - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        volumes:
          - '/home/crmdata/mariadb_data:/bitnami'
    suitecrm:
        image: 'bitnami/suitecrm:latest'
        environment:
          - MARIADB_HOST=mariadb
          - MARIADB_PORT_NUMBER=3306
          - SUITECRM_DATABASE_USER=${DATABASE_USER}
          - SUITECRM_DATABASE_NAME=bitnami_suitecrm
          - SUITECRM_DATABASE_PASSWORD=${DATABASE_PASSWORD}
          - VIRTUAL_HOST=${HOST}
          - LETSENCRYPT_HOST=${HOST}
          - LETSENCRYPT_EMAIL=${EMAIL}
        volumes:
          - '/home/crmdata/suitecrm_data:/bitnami'
        depends_on:
          - mariadb
    proxy:
        image: 'jwilder/nginx-proxy:alpine'
        restart: always
        ports:
          - 80:80
          - 443:443
        labels:
          com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        volumes:
          - certs:/etc/nginx/certs:ro
          - conf.d:/etc/nginx/conf.d
          - vhost.d:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
          - /var/run/docker.sock:/tmp/docker.sock:ro
    letsencrypt-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
          - certs:/etc/nginx/certs
          - conf.d:/etc/nginx/conf.d
          - vhost.d:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
          - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
          - proxy
volumes:
    mariadb_data:
        driver: local
    suitecrm_data:
        driver: local
    certs:
    conf.d:
    vhost.d:
    html:
